export const LOAD_INITIAL_ORDERS = 'LOAD_INITIAL_ORDERS';

export const CREATE_LINE_ITEM = 'CREATE_LINE_ITEM';
export const UPDATE_LINE_ITEM = 'UPDATE_LINE_ITEM';
export const DELETE_LINE_ITEM = 'DELETE_LINE_ITEM';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const RESET_ORDERS = 'RESET_ORDERS'

export const LOAD_INITIAL_PRODUCTS = 'LOAD_INITIAL_PRODUCTS';

export const SET_AUTH = 'SET_AUTH';

export const LOAD_INITIAL_USERS = 'LOAD_INITIAL_USERS';
